---
title: "DPS Assignemnt1"
output:
  html_document:
    df_print: paged
---

Importing cs files from document


```{r}
#install.packages("dplyr")
#install.packages(c("ggplot2", "ggpubr", "tidyverse", "broom", "AICcmodavg"))

library(dplyr)
#library(ggpubr)
#library(tidyverse)
#library(broom)
#library(AICcmodavg)
library(ggplot2)

```

we sent 0 for article setting and 1 for new settings
```{r}


hibench_Wordcount_small_article_settings <- read.csv("../experiments/hibench_wordcount_14workers_1master_original_small.report", sep="")
hibench_Wordcount_small_new_settings <- read.csv("../experiments/hibench_wordcount_14workers_1master_small_new.report", sep="")

hibench_Wordcount_small_article_settings["dataset"] <- "0.32GB"
hibench_Wordcount_small_article_settings["settings"]<- "0"

hibench_Wordcount_small_new_settings["dataset"] <- "0.32GB"
hibench_Wordcount_small_new_settings["settings"]<- "1" 


hibench_Wordcount_large_article_settings <- read.csv("../experiments/hibench_wordcount_14workers_1master_original_large.report", sep="")
hibench_Wordcount_large_new_settings <- read.csv("../experiments/hibench_wordcount_14workers_1master_new_large.report", sep="")

hibench_Wordcount_large_article_settings["dataset"] <- "3.2GB"
hibench_Wordcount_large_article_settings["settings"]<- "0"

hibench_Wordcount_large_new_settings["dataset"] <- "3.2GB"
hibench_Wordcount_large_new_settings["settings"]<- "1" 

hibench_Wordcount_huge_article_settings <- read.csv("../experiments/hibench_wordcount_14workers_1master_original_huge.report", sep="")
hibench_Wordcount_huge_new_settings <- read.csv("../experiments/hibench_wordcount_14workers_1master_new_huge.report", sep="")

hibench_Wordcount_huge_article_settings["dataset"] <- "32GB"
hibench_Wordcount_huge_article_settings["settings"]<- "0"

hibench_Wordcount_huge_new_settings["dataset"] <- "32GB"
hibench_Wordcount_huge_new_settings["settings"]<- "1" 

```

Summary statistics are located at the end of the file

joining dfs together
```{r}

df_article_settings = rbind(hibench_Wordcount_large_article_settings, hibench_Wordcount_small_article_settings, hibench_Wordcount_huge_article_settings)
df_new_setting = rbind(hibench_Wordcount_large_new_settings, hibench_Wordcount_small_new_settings, hibench_Wordcount_huge_new_settings)


df_article_settings_box = df_article_settings
df_new_settings_box = df_new_setting

df_article_settings_bar = df_article_settings
df_new_settings_bar = df_new_setting

```

now create 2 box plots 

```{r}
article_setting_box <- ggplot(df_article_settings_box, aes(x = dataset, y = Duration.s.)) +
  geom_boxplot() + xlab("Size of dataset") + ylab("Duration (seconds)") + scale_x_discrete(limits=c("0.32GB","3.2GB","32GB")) + expand_limits(x = 0, y = 0)# + ggtitle("Word count performance with Article Settings") 


article_setting_box
 
new_setting_box <- ggplot(df_new_settings_box, aes(x = dataset, y =Duration.s.)) +
  geom_boxplot()   + xlab("Size of dataset") + ylab("Duration (seconds)") + scale_x_discrete(limits=c("0.32GB","3.2GB","32GB")) + expand_limits(x = 0, y = 0)#+ ggtitle("Word count performace with Our Settings")

new_setting_box 
 

```

